// <auto-generated />
using System;
using Focus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Focus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006111643_AddUserDeviceSessionTracking")]
    partial class AddUserDeviceSessionTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Focus.Domain.Entities.AgentMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("UserId");

                    b.ToTable("AgentMemories", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CoinPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GridHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("GridWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsInteractive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RequiredLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("catalog_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "desk_retro_oak",
                            Category = 1,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7325),
                            Description = "Klasik ahşap çalışma masası",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = false,
                            Name = "Retro Meşe Masa",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/items/desk_retro_oak.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "desk_minimal_white",
                            Category = 1,
                            CoinPrice = 80,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7505),
                            Description = "Modern ve ferah çalışma alanı",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = false,
                            Name = "Minimal Beyaz Masa",
                            RequiredLevel = 3,
                            SpriteUrl = "/sprites/items/desk_minimal_white.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "desk_cyber_neon",
                            Category = 1,
                            CoinPrice = 250,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7506),
                            Description = "Gelecekten gelen neon aydınlatmalı masa",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = false,
                            Name = "Siberpunk Neon Masa",
                            RequiredLevel = 8,
                            SpriteUrl = "/sprites/items/desk_cyber_neon.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "desk_gold_master",
                            Category = 1,
                            CoinPrice = 1000,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7507),
                            Description = "Saf altın kaplama usta çalışma masası",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = false,
                            Name = "Altın Büyük Üstat Masası",
                            RequiredLevel = 25,
                            SpriteUrl = "/sprites/items/desk_gold_master.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "chair_ergonomic_black",
                            Category = 2,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7508),
                            Description = "Omurgayı destekleyen siyah çalışma koltuğu",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Ergonomik Koltuk",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/items/chair_ergonomic_black.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "chair_vintage_leather",
                            Category = 2,
                            CoinPrice = 120,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7508),
                            Description = "Konforlu taba rengi deri koltuk",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Vintage Deri Koltuk",
                            RequiredLevel = 4,
                            SpriteUrl = "/sprites/items/chair_vintage_leather.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "chair_gaming_rgb",
                            Category = 2,
                            CoinPrice = 300,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7509),
                            Description = "Yumuşak dolgulu renkli oyuncu koltuğu",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "RGB Oyuncu Koltuğu",
                            RequiredLevel = 10,
                            SpriteUrl = "/sprites/items/chair_gaming_rgb.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "lamp_desk_brass",
                            Category = 3,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7510),
                            Description = "Masaya sıcak bir ışık huzmesi veren lamba",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = true,
                            Name = "Pirinç Masa Lambası",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/items/lamp_desk_brass.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "plant_bonsai",
                            Category = 3,
                            CoinPrice = 60,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7511),
                            Description = "Masada sakinlik veren minyatür bonsai ağacı",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Zen Bonsai Ağacı",
                            RequiredLevel = 2,
                            SpriteUrl = "/sprites/items/plant_bonsai.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "plant_monstera",
                            Category = 3,
                            CoinPrice = 90,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7511),
                            Description = "Odaya ferahlık katan geniş yapraklı bitki",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Büyük Monstera",
                            RequiredLevel = 5,
                            SpriteUrl = "/sprites/items/plant_monstera.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "neon_sign_focus",
                            Category = 3,
                            CoinPrice = 180,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7512),
                            Description = "Duvara asılan mor neon tabela",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = true,
                            Name = "Neon FOCUS Tabelası",
                            RequiredLevel = 6,
                            SpriteUrl = "/sprites/items/neon_sign_focus.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "record_player_vintage",
                            Category = 3,
                            CoinPrice = 220,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7513),
                            Description = "Lo-Fi çalan ahşap nostaljik plak çalar",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = true,
                            Name = "Retro Plak Çalar",
                            RequiredLevel = 7,
                            SpriteUrl = "/sprites/items/record_player_vintage.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "coffee_machine",
                            Category = 3,
                            CoinPrice = 280,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7513),
                            Description = "Taze kahve hazırlayan espresso makinesi",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = true,
                            Name = "Espresso Kahve Barı",
                            RequiredLevel = 9,
                            SpriteUrl = "/sprites/items/coffee_machine.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "bookshelf_wood",
                            Category = 3,
                            CoinPrice = 150,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7514),
                            Description = "Ciltli kitaplarla dolu ahşap kitaplık",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = false,
                            Name = "Klasik Ahşap Kitaplık",
                            RequiredLevel = 4,
                            SpriteUrl = "/sprites/items/bookshelf_wood.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "fireplace_cozy",
                            Category = 3,
                            CoinPrice = 400,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7515),
                            Description = "Odayı ısıtan ve çıtırtı sesleri veren şömine",
                            GridHeight = 1,
                            GridWidth = 2,
                            IsInteractive = true,
                            Name = "Çıtırtılı Taş Şömine",
                            RequiredLevel = 12,
                            SpriteUrl = "/sprites/items/fireplace_cozy.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "tshirt_basic_white",
                            Category = 4,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7516),
                            Description = "Sade pamuklu beyaz tişört",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Temel Beyaz Tişört",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/avatar/tshirt_white.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "hoodie_gray",
                            Category = 4,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7516),
                            Description = "Rahat gri kapüşonlu sweatshirt",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Gri Kapüşonlu",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/avatar/hoodie_gray.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "sweater_warm",
                            Category = 4,
                            CoinPrice = 50,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7517),
                            Description = "Kahverengi örgü sıcak kazak",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Sıcak Örgü Kazak",
                            RequiredLevel = 2,
                            SpriteUrl = "/sprites/avatar/sweater_warm.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "hoodie_cyber_neon",
                            Category = 4,
                            CoinPrice = 200,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7518),
                            Description = "Karanlıkta parlayan neon şeritli özel kapüşonlu",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Siberpunk Neon Hoodie",
                            RequiredLevel = 7,
                            SpriteUrl = "/sprites/avatar/hoodie_cyber_neon.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "jacket_leather_vintage",
                            Category = 4,
                            CoinPrice = 350,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7518),
                            Description = "Retro kahverengi şık deri ceket",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Vintage Deri Ceket",
                            RequiredLevel = 11,
                            SpriteUrl = "/sprites/avatar/jacket_leather_vintage.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "jeans_basic_blue",
                            Category = 4,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7519),
                            Description = "Klasik düz kesim mavi kot pantolon",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Temel Mavi Kot",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/avatar/jeans_blue.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "jeans_dark",
                            Category = 4,
                            CoinPrice = 45,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7520),
                            Description = "Koyu indigo rengi şık kot pantolon",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Koyu Kot Pantolon",
                            RequiredLevel = 2,
                            SpriteUrl = "/sprites/avatar/jeans_dark.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "jogger_black",
                            Category = 4,
                            CoinPrice = 65,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7520),
                            Description = "Çalışma seansları için rahat siyah jogger",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Siyah Eşofman",
                            RequiredLevel = 4,
                            SpriteUrl = "/sprites/avatar/jogger_black.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "sneakers_white",
                            Category = 4,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7521),
                            Description = "Rahat beyaz spor ayakkabı",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Beyaz Spor Ayakkabı",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/avatar/sneakers_white.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "boots_leather_brown",
                            Category = 4,
                            CoinPrice = 80,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7522),
                            Description = "Klasik dayanıklı deri bot",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Kahverengi Deri Bot",
                            RequiredLevel = 5,
                            SpriteUrl = "/sprites/avatar/boots_brown.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "beanie_orange",
                            Category = 5,
                            CoinPrice = 40,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7522),
                            Description = "Örgü sıcak turuncu bere",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Sıcak Turuncu Bere",
                            RequiredLevel = 2,
                            SpriteUrl = "/sprites/avatar/beanie_orange.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "cap_black",
                            Category = 5,
                            CoinPrice = 45,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7523),
                            Description = "Spor tarz siyah kep",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Siyah Klasik Kep",
                            RequiredLevel = 3,
                            SpriteUrl = "/sprites/avatar/cap_black.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "glasses_retro_round",
                            Category = 5,
                            CoinPrice = 75,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7524),
                            Description = "Metal çerçeveli yuvarlak gözlük",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Retro Yuvarlak Gözlük",
                            RequiredLevel = 4,
                            SpriteUrl = "/sprites/avatar/glasses_round.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "headphones_pro",
                            Category = 5,
                            CoinPrice = 220,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7524),
                            Description = "Gürültü engelleyici profesyonel kafa üstü kulaklık",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Stüdyo Kulaklığı",
                            RequiredLevel = 8,
                            SpriteUrl = "/sprites/avatar/headphones_pro.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "wallpaper_brick_white",
                            Category = 6,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7525),
                            Description = "Aydınlık ve ferah beyaz tuğla",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Beyaz Tuğla Duvar",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/walls/brick_white.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "wallpaper_brick_loft",
                            Category = 6,
                            CoinPrice = 70,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7525),
                            Description = "Kırmızı tuğla loft duvar kağıdı",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Endüstriyel Loft Tuğla",
                            RequiredLevel = 3,
                            SpriteUrl = "/sprites/walls/brick_loft.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "wallpaper_slate_dark",
                            Category = 6,
                            CoinPrice = 100,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7526),
                            Description = "Modern koyu gri arduvaz taş kaplama",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Koyu Arduvaz Duvar",
                            RequiredLevel = 5,
                            SpriteUrl = "/sprites/walls/slate_dark.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "wallpaper_wood_cozy",
                            Category = 6,
                            CoinPrice = 120,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7527),
                            Description = "Ahşap panel kaplama sıcak duvar",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Sıcak Doğal Ahşap Duvar",
                            RequiredLevel = 6,
                            SpriteUrl = "/sprites/walls/wood_cozy.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "floor_parquet_oak",
                            Category = 7,
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7528),
                            Description = "Açık renk dayanıklı meşe parke",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Doğal Meşe Parke",
                            RequiredLevel = 1,
                            SpriteUrl = "/sprites/floors/parquet_oak.png",
                            Tier = 1
                        },
                        new
                        {
                            Id = "floor_tatami_japanese",
                            Category = 7,
                            CoinPrice = 90,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7530),
                            Description = "Hasır dokulu geleneksel Japon zemin kaplaması",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Japon Tatami Zemin",
                            RequiredLevel = 4,
                            SpriteUrl = "/sprites/floors/tatami.png",
                            Tier = 2
                        },
                        new
                        {
                            Id = "floor_marble_white",
                            Category = 7,
                            CoinPrice = 180,
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 157, DateTimeKind.Utc).AddTicks(7531),
                            Description = "Zarif damarlı beyaz mermer zemin",
                            GridHeight = 1,
                            GridWidth = 1,
                            IsInteractive = false,
                            Name = "Lüks Beyaz Mermer",
                            RequiredLevel = 8,
                            SpriteUrl = "/sprites/floors/marble_white.png",
                            Tier = 2
                        });
                });

            modelBuilder.Entity("Focus.Domain.Entities.CoinLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("coin_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("integer");

                    b.Property<int>("FocusMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MixPresetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TargetRounds")
                        .HasColumnType("integer");

                    b.Property<string>("ThemeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalPausedSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("focus_sessions", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.PixelRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxVisitors")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WallPaperId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("pixel_rooms", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomGuestbookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GiftType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyRoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("StudyRoomId");

                    b.ToTable("RoomGuestbookEntries", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("InviteeUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteeUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("RoomId");

                    b.ToTable("room_invitations", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GridX")
                        .HasColumnType("integer");

                    b.Property<int>("GridY")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rotation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_items", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFocusing")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SeatIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique();

                    b.ToTable("room_members", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.SessionCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetIntent")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionCheckIns", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.SessionReflection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistractionNote")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<int>("FocusQuality")
                        .HasColumnType("integer");

                    b.Property<string>("MoodAfter")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionReflections", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.StudyRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("MusicTrackId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThemeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("study_rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cf04f25-240d-47d9-b299-fc9a1866692a"),
                            Code = "LIB-LOFI",
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 158, DateTimeKind.Utc).AddTicks(9009),
                            Description = "Hafif yağmur sesi ve yumuşak lo-fi ritimleriyle sessiz kütüphane ortamı.",
                            IsPrivate = false,
                            MaxCapacity = 20,
                            MusicTrackId = "Midnight Lofi Study",
                            Name = "Sessiz Kütüphane - Lo-Fi Salonu",
                            ThemeId = "rainy_window",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("8174bf8d-0745-47c7-8ac5-c17a0449f46d"),
                            Code = "LIB-WOOD",
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 158, DateTimeKind.Utc).AddTicks(9179),
                            Description = "Sıcak ahşap paneller, kitap kokusu ve huzurlu akustik tınılar.",
                            IsPrivate = false,
                            MaxCapacity = 20,
                            MusicTrackId = "Acoustic Focus Guitar",
                            Name = "Akustik Arşiv - Ahşap Salon",
                            ThemeId = "cozy_fireplace",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("16da55f1-1228-4822-8e8c-2447559af1b1"),
                            Code = "LIB-NIGHT",
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 158, DateTimeKind.Utc).AddTicks(9181),
                            Description = "Gece çalışanlar için neon ve karanlık tema, derin odaklanma ambiyansı.",
                            IsPrivate = false,
                            MaxCapacity = 20,
                            MusicTrackId = "Deep Cyber Ambient",
                            Name = "Gece Kuşu Salonu - Siber Kütüphane",
                            ThemeId = "neon_city_night",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00ff7f58-28ad-42f5-89fa-8d8585f417e8"),
                            Code = "SHOP-BAZAAR",
                            CreatedAt = new DateTime(2026, 10, 6, 11, 16, 43, 159, DateTimeKind.Utc).AddTicks(375),
                            Description = "Yeni mobilyaların, aksesuarların ve kıyafetlerin sergilendiği canlı piksel çarşı.",
                            IsPrivate = false,
                            MaxCapacity = 50,
                            MusicTrackId = "market_chill",
                            Name = "Piksel Çarşı & Mobilya Pazarı",
                            ThemeId = "cozy_bazaar",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Focus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("tr-TR");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Europe/Istanbul");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL AND \"Email\" IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserAvatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BottomItemCatalogId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlassesItemCatalogId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HairStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HatItemCatalogId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShoesItemCatalogId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TopItemCatalogId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_avatars", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserDeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceSessions", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CatalogItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("UserId", "CatalogItemId");

                    b.ToTable("user_inventory_items", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AgentEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CityKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DefaultFocusMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("FlowShieldEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ShortBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("TargetRounds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WeatherSyncEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FreezesAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFreezeUsedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_streaks", (string)null);
                });

            modelBuilder.Entity("Focus.Domain.Entities.AgentMemory", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Focus.Domain.Entities.CoinLedgerEntry", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.FocusSession", b =>
                {
                    b.HasOne("Focus.Domain.Entities.PixelRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.PixelRoom", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "OwnerUser")
                        .WithOne("Room")
                        .HasForeignKey("Focus.Domain.Entities.PixelRoom", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Focus.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomGuestbookEntry", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focus.Domain.Entities.StudyRoom", "StudyRoom")
                        .WithMany()
                        .HasForeignKey("StudyRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderUser");

                    b.Navigation("StudyRoom");
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomInvitation", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "Invitee")
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Focus.Domain.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focus.Domain.Entities.StudyRoom", "Room")
                        .WithMany("Invitations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomItem", b =>
                {
                    b.HasOne("Focus.Domain.Entities.PixelRoom", "Room")
                        .WithMany("Items")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Focus.Domain.Entities.RoomMember", b =>
                {
                    b.HasOne("Focus.Domain.Entities.StudyRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.SessionCheckIn", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focus.Domain.Entities.SessionReflection", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Focus.Domain.Entities.StudyRoom", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserAvatar", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithOne("Avatar")
                        .HasForeignKey("Focus.Domain.Entities.UserAvatar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserDeviceSession", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserInventoryItem", b =>
                {
                    b.HasOne("Focus.Domain.Entities.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Focus.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UserStreak", b =>
                {
                    b.HasOne("Focus.Domain.Entities.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("Focus.Domain.Entities.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Focus.Domain.Entities.PixelRoom", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Focus.Domain.Entities.StudyRoom", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Focus.Domain.Entities.User", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("ExternalLogins");

                    b.Navigation("InventoryItems");

                    b.Navigation("Preferences");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Room");

                    b.Navigation("Streak");
                });
#pragma warning restore 612, 618
        }
    }
}
